[versions]
minecraft = "1.21.10"
fabric-loader = "0.17.2"
neoforge-loader = "10.0.18"
fabric-api = "0.133.14+1.21.9"
mappings-yalmm = "2"
mappings-parchment = "2024.07.28"

# Dependencies
yumi-commons = "1.0.0"
yumi-mc-foundation = "1.0.0-alpha.17+1.21.9"
spruceui = "9.0.0+1.21.9"
<<<<<<< HEAD
modmenu = "15.0.0-beta.1"
=======
pridelib = "1.5.1+1.21.9"

modmenu = "16.0.0-rc.1"
>>>>>>> 1c43f316f491fa4a0c1f1312b0f04816fe3bed9a
trinkets = "3.10.0"
accessories = "1.3.3-beta+1.21.8"

# Configuration
nightconfig = "3.8.1"

# Gradle
gradle-licenser = "2.1.+"
gradle-loom = "1.11.+"
gradle-lambdamcdev = "1.8.+"
gson = "2.11.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
neoforge-loader = { module = "net.neoforged.fancymodloader:loader", version.ref = "neoforge-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

# Dependencies
yumi-commons-core = { module = "dev.yumi.commons:yumi-commons-core", version.ref = "yumi-commons" }
yumi-commons-collections = { module = "dev.yumi.commons:yumi-commons-collections", version.ref = "yumi-commons" }
yumi-commons-event = { module = "dev.yumi.commons:yumi-commons-event", version.ref = "yumi-commons" }
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
trinkets = { module = "dev.emi:trinkets", version.ref = "trinkets" }
accessories = { module = "io.wispforest:accessories-fabric", version.ref = "accessories" }

# Configuration
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

# Gradle
gradle-licenser = { module = "dev.yumi:yumi-gradle-licenser", version.ref = "gradle-licenser" }
gradle-loom = { module = "net.fabricmc:fabric-loom", version.ref = "gradle-loom" }
gradle-lambdamcdev = { module = "dev.lambdaurora.mcdev:dev.lambdaurora.mcdev.gradle.plugin", version.ref = "gradle-lambdamcdev" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
