name: "Release"

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v4
      - name: "Build with Gradle"
        run: ./gradlew build packageModrinth --parallel --stacktrace
        env:
          MODRINTH_TOKEN: "dummy"
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: ./build/libs/
      - name: "Upload Modrinth artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: Modrinth
          path: ./build/modrinth.zip
          retention-days: 1

  github:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          name: Modrinth
          path: dist
      - name: "Extract files"
        run: unzip dist/modrinth.zip
      - id: files
        name: "Read which files to upload"
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            const { default: fs } = await import("node:fs/promises");
            const json = JSON.parse(await fs.readFile("manifest.json", { encoding: "utf8" }));
            return json.files.map(it => `"${it}"`).join(" ");
      - name: "Upload artifacts to GitHub release"
        run: gh release upload "${{ github.ref_name }}" ${{ steps.files.outputs.result }}

  modrinth:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
        with:
          name: Modrinth
          path: dist
      - name: "Extract files"
        run: unzip dist/modrinth.zip
      - name: "Release on Modrinth"
        uses: LambdAurora/modrinth_publish@v0.1.5
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: "yBW8D80W"
          manifest: "manifest.json"
          readme_file: "README.md"

  curseforge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: "Set up Gradle"
        uses: gradle/actions/setup-gradle@v4
      - name: "Release on CurseForge"
        run: ./gradlew curseforge --parallel --stacktrace
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
